# F1 Podium Prediction — Milestone 1

Goal: for each driver in each race, predict whether they finish on the podium
(`results.positionOrder <= 3`), using only information available after qualifying.

This notebook currently covers **Setup**, **Data Loading** and the **Raw Data Audit**.
The audit only *measures* the raw data; it does not clean or decide anything.
Reusable code lives in `src/f1podium/`.

## 1. Setup

Make the `src/` folder importable. We search upwards from the current folder so the
same cell works when run from `notebooks/`, from the repo root, or on Kaggle
(where `src/` must be provided alongside the notebook).

In [1]:
import sys
from pathlib import Path

def _add_src_to_path() -> Path:
    for base in [Path.cwd(), *Path.cwd().parents]:
        if (base / "src" / "f1podium").is_dir():
            src = base / "src"
            if str(src) not in sys.path:
                sys.path.insert(0, str(src))
            return src
    raise FileNotFoundError("Could not find src/f1podium above " + str(Path.cwd()))

SRC_DIR = _add_src_to_path()

%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np
import pandas as pd
from IPython.display import display

from f1podium import config
from f1podium.load import load_all
from f1podium.validate import (
    find_duplicates,
    missing_summary,
    run_foreign_key_checks,
    run_primary_key_checks,
)

pd.set_option("display.max_rows", 250)
pd.set_option("display.max_columns", 50)
pd.set_option("display.width", 200)

np.random.seed(config.RANDOM_SEED)

print("Python     :", sys.version.split()[0], "|", sys.executable)
print("pandas     :", pd.__version__)
print("src        :", SRC_DIR)
print("raw data   :", config.RAW_DIR)
print("split      : train <=", config.TRAIN_END_YEAR, "| val", config.VAL_YEARS,
      "| test >=", config.TEST_START_YEAR)
print("seed       :", config.RANDOM_SEED)

Python     : 3.13.7 | C:\Users\yshim\dev\f1-podium\.venv\Scripts\python.exe
pandas     : 3.0.6
src        : C:\Users\yshim\dev\f1-podium\src
raw data   : C:\Users\yshim\dev\f1-podium\data\raw
split      : train <= 2019 | val (2020, 2021) | test >= 2022
seed       : 42

## 2. Data Loading

`load_all()` reads the 14 CSVs with an explicit schema per table:
`\N` (and empty fields) become missing; IDs/counts use nullable `Int64`;
text uses `string`; dates are parsed strictly with `%Y-%m-%d`.
The loader raises if a file's columns differ from the declared schema.

In [3]:
tables = load_all()

load_summary = pd.DataFrame(
    {
        "rows": {n: len(df) for n, df in tables.items()},
        "columns": {n: df.shape[1] for n, df in tables.items()},
        "memory_MB": {n: round(df.memory_usage(deep=True).sum() / 1e6, 2) for n, df in tables.items()},
    }
).rename_axis("table")
display(load_summary)

                         rows  columns  memory_MB
table
circuits                   77        9       0.03
constructor_results     12625        5       1.15
constructor_standings   13391        7       1.38
constructors              212        5       0.06
driver_standings        34863        7       3.62
drivers                   861        9       0.34
lap_times              589081        6      60.09
pit_stops               11371        7       1.79
qualifying              10494        9       2.35
races                    1125       18       0.66
results                 26759       18       7.91
seasons                    75        2       0.01
sprint_results            360       16       0.10
status                    139        2       0.01

Declared dtypes of the three tables we will use most:

In [4]:
for name in ["races", "results", "qualifying"]:
    print(f"--- {name}")
    print(tables[name].dtypes.to_string(), end="\n\n")

--- races
raceId                  Int64
year                    Int64
round                   Int64
circuitId               Int64
name                   string
date           datetime64[us]
time                   string
url                    string
fp1_date       datetime64[us]
fp1_time               string
fp2_date       datetime64[us]
fp2_time               string
fp3_date       datetime64[us]
fp3_time               string
quali_date     datetime64[us]
quali_time             string
sprint_date    datetime64[us]
sprint_time            string

--- results
resultId             Int64
raceId               Int64
driverId             Int64
constructorId        Int64
number               Int64
grid                 Int64
position             Int64
positionText        string
positionOrder        Int64
points             float64
laps                 Int64
time                string
milliseconds         Int64
fastestLap           Int64
rank                 Int64
fastestLapTime      string
fastestLapSpeed    float64
statusId             Int64

--- qualifying
qualifyId         Int64
raceId            Int64
driverId          Int64
constructorId     Int64
number            Int64
position          Int64
q1               string
q2               string
q3               string

In [5]:
# Short aliases used throughout the audit
races = tables["races"]
results = tables["results"]
qualifying = tables["qualifying"]

def with_year(df: pd.DataFrame) -> pd.DataFrame:
    """Attach races.year, checking the join neither drops nor duplicates rows."""
    out = df.merge(races[["raceId", "year"]], on="raceId", how="left", validate="many_to_one")
    assert len(out) == len(df), "join changed the row count"
    assert out["year"].notna().all(), "some rows have a raceId not in races"
    return out

## 3. Raw Data Audit

### 3.1 Missing values per column

Count and percentage of missing values for every column of every table
(after treating `\N` and empty fields as missing).

In [6]:
missing = missing_summary(tables)
display(missing.sort_values(["table", "pct_missing"], ascending=[True, False]).reset_index(drop=True))

                     table                  column           dtype  n_rows  n_missing  pct_missing
0                 circuits               circuitId           Int64      77          0         0.00
1                 circuits              circuitRef          string      77          0         0.00
2                 circuits                    name          string      77          0         0.00
3                 circuits                location          string      77          0         0.00
4                 circuits                 country          string      77          0         0.00
5                 circuits                     lat         float64      77          0         0.00
6                 circuits                     lng         float64      77          0         0.00
7                 circuits                     alt           Int64      77          0         0.00
8                 circuits                     url          string      77          0         0.00
9      constructor_results                  status          string   12625      12608        99.87
10     constructor_results    constructorResultsId           Int64   12625          0         0.00
11     constructor_results                  raceId           Int64   12625          0         0.00
12     constructor_results           constructorId           Int64   12625          0         0.00
13     constructor_results                  points         float64   12625          0         0.00
14   constructor_standings  constructorStandingsId           Int64   13391          0         0.00
15   constructor_standings                  raceId           Int64   13391          0         0.00
16   constructor_standings           constructorId           Int64   13391          0         0.00
17   constructor_standings                  points         float64   13391          0         0.00
18   constructor_standings                position           Int64   13391          0         0.00
19   constructor_standings            positionText          string   13391          0         0.00
20   constructor_standings                    wins           Int64   13391          0         0.00
21            constructors           constructorId           Int64     212          0         0.00
22            constructors          constructorRef          string     212          0         0.00
23            constructors                    name          string     212          0         0.00
24            constructors             nationality          string     212          0         0.00
25            constructors                     url          string     212          0         0.00
26        driver_standings       driverStandingsId           Int64   34863          0         0.00
27        driver_standings                  raceId           Int64   34863          0         0.00
28        driver_standings                driverId           Int64   34863          0         0.00
29        driver_standings                  points         float64   34863          0         0.00
30        driver_standings                position           Int64   34863          0         0.00
31        driver_standings            positionText          string   34863          0         0.00
32        driver_standings                    wins           Int64   34863          0         0.00
33                 drivers                  number           Int64     861        802        93.15
34                 drivers                    code          string     861        757        87.92
35                 drivers                driverId           Int64     861          0         0.00
36                 drivers               driverRef          string     861          0         0.00
37                 drivers                forename          string     861          0         0.00
38                 drivers                 surname          string     861          0         0.00
39                 drivers                     dob  datetime64[us]     861          0         0.00
40                 drivers             nationality          string     861          0         0.00
41                 drivers                     url          string     861          0         0.00
42               lap_times                  raceId           Int64  589081          0         0.00
43               lap_times                driverId           Int64  589081          0         0.00
44               lap_times                     lap           Int64  589081          0         0.00
45               lap_times                position           Int64  589081          0         0.00
46               lap_times                    time          string  589081          0         0.00
47               lap_times            milliseconds           Int64  589081          0         0.00
48               pit_stops                  raceId           Int64   11371          0         0.00
49               pit_stops                driverId           Int64   11371          0         0.00
50               pit_stops                    stop           Int64   11371          0         0.00
51               pit_stops                     lap           Int64   11371          0         0.00
52               pit_stops                    time          string   11371          0         0.00
53               pit_stops                duration          string   11371          0         0.00
54               pit_stops            milliseconds           Int64   11371          0         0.00
55              qualifying                      q3          string   10494       6865        65.42
56              qualifying                      q2          string   10494       4647        44.28
57              qualifying                      q1          string   10494        156         1.49
58              qualifying               qualifyId           Int64   10494          0         0.00
59              qualifying                  raceId           Int64   10494          0         0.00
60              qualifying                driverId           Int64   10494          0         0.00
61              qualifying           constructorId           Int64   10494          0         0.00
62              qualifying                  number           Int64   10494          0         0.00
63              qualifying                position           Int64   10494          0         0.00
64                   races             sprint_time          string    1125       1110        98.67
65                   races             sprint_date  datetime64[us]    1125       1107        98.40
66                   races                fp3_time          string    1125       1072        95.29
67                   races                fp1_time          string    1125       1057        93.96
68                   races                fp2_time          string    1125       1057        93.96
69                   races              quali_time          string    1125       1057        93.96
70                   races                fp3_date  datetime64[us]    1125       1053        93.60
71                   races                fp1_date  datetime64[us]    1125       1035        92.00
72                   races                fp2_date  datetime64[us]    1125       1035        92.00
73                   races              quali_date  datetime64[us]    1125       1035        92.00
74                   races                    time          string    1125        731        64.98
75                   races                  raceId           Int64    1125          0         0.00
76                   races                    year           Int64    1125          0         0.00
77                   races                   round           Int64    1125          0         0.00
78                   races               circuitId           Int64    1125          0         0.00
79                   races                    name          string    1125          0         0.00
80                   races                    date  datetime64[us]    1125          0         0.00
81                   races                     url          string    1125          0         0.00
82                 results                    time          string   26759      19079        71.30
83                 results            milliseconds           Int64   26759      19079        71.30
84                 results              fastestLap           Int64   26759      18507        69.16
85                 results          fastestLapTime          string   26759      18507        69.16
86                 results         fastestLapSpeed         float64   26759      18507        69.16
87                 results                    rank           Int64   26759      18249        68.20
88                 results                position           Int64   26759      10953        40.93
89                 results                  number           Int64   26759          6         0.02
90                 results                resultId           Int64   26759          0         0.00
91                 results                  raceId           Int64   26759          0         0.00
92                 results                driverId           Int64   26759          0         0.00
93                 results           constructorId           Int64   26759          0         0.00
94                 results                    grid           Int64   26759          0         0.00
95                 results            positionText          string   26759          0         0.00
96                 results           positionOrder           Int64   26759          0         0.00
97                 results                  points         float64   26759          0         0.00
98                 results                    laps           Int64   26759          0         0.00
99                 results                statusId           Int64   26759          0         0.00
100                seasons                    year           Int64      75          0         0.00
101                seasons                     url          string      75          0         0.00
102         sprint_results                    time          string     360         20         5.56
103         sprint_results            milliseconds           Int64     360         20         5.56
104         sprint_results                position           Int64     360         15         4.17
105         sprint_results              fastestLap           Int64     360          9         2.50
106         sprint_results          fastestLapTime          string     360          9         2.50
107         sprint_results                resultId           Int64     360          0         0.00
108         sprint_results                  raceId           Int64     360          0         0.00
109         sprint_results                driverId           Int64     360          0         0.00
110         sprint_results           constructorId           Int64     360          0         0.00
111         sprint_results                  number           Int64     360          0         0.00
112         sprint_results                    grid           Int64     360          0         0.00
113         sprint_results            positionText          string     360          0         0.00
114         sprint_results           positionOrder           Int64     360          0         0.00
115         sprint_results                  points         float64     360          0         0.00
116         sprint_results                    laps           Int64     360          0         0.00
117         sprint_results                statusId           Int64     360          0         0.00
118                 status                statusId           Int64     139          0         0.00
119                 status                  status          string     139          0         0.00

Only the columns that have at least one missing value, worst first:

In [7]:
display(
    missing[missing["n_missing"] > 0]
    .sort_values("pct_missing", ascending=False)
    .reset_index(drop=True)
)

                  table           column           dtype  n_rows  n_missing  pct_missing
0   constructor_results           status          string   12625      12608        99.87
1                 races      sprint_time          string    1125       1110        98.67
2                 races      sprint_date  datetime64[us]    1125       1107        98.40
3                 races         fp3_time          string    1125       1072        95.29
4                 races         fp1_time          string    1125       1057        93.96
5                 races         fp2_time          string    1125       1057        93.96
6                 races       quali_time          string    1125       1057        93.96
7                 races         fp3_date  datetime64[us]    1125       1053        93.60
8               drivers           number           Int64     861        802        93.15
9                 races         fp1_date  datetime64[us]    1125       1035        92.00
10                races       quali_date  datetime64[us]    1125       1035        92.00
11                races         fp2_date  datetime64[us]    1125       1035        92.00
12              drivers             code          string     861        757        87.92
13              results             time          string   26759      19079        71.30
14              results     milliseconds           Int64   26759      19079        71.30
15              results       fastestLap           Int64   26759      18507        69.16
16              results  fastestLapSpeed         float64   26759      18507        69.16
17              results   fastestLapTime          string   26759      18507        69.16
18              results             rank           Int64   26759      18249        68.20
19           qualifying               q3          string   10494       6865        65.42
20                races             time          string    1125        731        64.98
21           qualifying               q2          string   10494       4647        44.28
22              results         position           Int64   26759      10953        40.93
23       sprint_results     milliseconds           Int64     360         20         5.56
24       sprint_results             time          string     360         20         5.56
25       sprint_results         position           Int64     360         15         4.17
26       sprint_results   fastestLapTime          string     360          9         2.50
27       sprint_results       fastestLap           Int64     360          9         2.50
28           qualifying               q1          string   10494        156         1.49
29              results           number           Int64   26759          6         0.02

### 3.2 Primary keys

A key passes if it has no nulls and no repeated values. Surrogate ids (e.g. `raceId`)
are listed first, then natural/composite keys, which say more about the data.
`results (raceId, driverId)` is **expected to fail**: early seasons have shared drives.

In [8]:
pk_results = run_primary_key_checks(tables)
display(pk_results)
print(f"{(~pk_results['passed']).sum()} of {len(pk_results)} primary-key checks failed")

                    table                     key  n_rows  n_null_key  n_duplicate_rows  passed
0                circuits               circuitId      77           0                 0    True
1            constructors           constructorId     212           0                 0    True
2                 drivers                driverId     861           0                 0    True
3                   races                  raceId    1125           0                 0    True
4                  status                statusId     139           0                 0    True
5                 seasons                    year      75           0                 0    True
6                 results                resultId   26759           0                 0    True
7          sprint_results                resultId     360           0                 0    True
8              qualifying               qualifyId   10494           0                 0    True
9        driver_standings       driverStandingsId   34863           0                 0    True
10  constructor_standings  constructorStandingsId   13391           0                 0    True
11    constructor_results    constructorResultsId   12625           0                 0    True
12               circuits              circuitRef      77           0                 0    True
13           constructors          constructorRef     212           0                 0    True
14                drivers               driverRef     861           0                 0    True
15                  races             year, round    1125           0                 0    True
16              lap_times   raceId, driverId, lap  589081           0                 0    True
17              pit_stops  raceId, driverId, stop   11371           0                 0    True
18       driver_standings        raceId, driverId   34863           0                 0    True
19  constructor_standings   raceId, constructorId   13391           0                 0    True
20    constructor_results   raceId, constructorId   12625           0                 0    True
21             qualifying        raceId, driverId   10494           0                 0    True
22                results        raceId, driverId   26759           0               176   False
23         sprint_results        raceId, driverId     360           0                 0    True

1 of 24 primary-key checks failed

### 3.3 Foreign keys

For each relationship: how many child rows have a null key, and how many point to an
id that does not exist in the parent table.

In [9]:
fk_results = run_foreign_key_checks(tables)
display(fk_results)
print(f"{(~fk_results['passed']).sum()} of {len(fk_results)} foreign-key checks failed")

                    child             fk                      parent  n_child_rows  n_null_fk  n_unmatched_rows  n_unmatched_distinct example_unmatched  passed
0                   races      circuitId          circuits.circuitId          1125          0                 0                     0                []    True
1                   races           year                seasons.year          1125          0                 0                     0                []    True
2                 results         raceId                races.raceId         26759          0                 0                     0                []    True
3                 results       driverId            drivers.driverId         26759          0                 0                     0                []    True
4                 results  constructorId  constructors.constructorId         26759          0                 0                     0                []    True
5          sprint_results         raceId                races.raceId           360          0                 0                     0                []    True
6          sprint_results       driverId            drivers.driverId           360          0                 0                     0                []    True
7          sprint_results  constructorId  constructors.constructorId           360          0                 0                     0                []    True
8              qualifying         raceId                races.raceId         10494          0                 0                     0                []    True
9              qualifying       driverId            drivers.driverId         10494          0                 0                     0                []    True
10             qualifying  constructorId  constructors.constructorId         10494          0                 0                     0                []    True
11                results       statusId             status.statusId         26759          0                 0                     0                []    True
12         sprint_results       statusId             status.statusId           360          0                 0                     0                []    True
13       driver_standings         raceId                races.raceId         34863          0                 0                     0                []    True
14       driver_standings       driverId            drivers.driverId         34863          0                 0                     0                []    True
15  constructor_standings         raceId                races.raceId         13391          0                 0                     0                []    True
16  constructor_standings  constructorId  constructors.constructorId         13391          0                 0                     0                []    True
17    constructor_results         raceId                races.raceId         12625          0                 0                     0                []    True
18    constructor_results  constructorId  constructors.constructorId         12625          0                 0                     0                []    True
19              lap_times         raceId                races.raceId        589081          0                 0                     0                []    True
20              lap_times       driverId            drivers.driverId        589081          0                 0                     0                []    True
21              pit_stops         raceId                races.raceId         11371          0                 0                     0                []    True
22              pit_stops       driverId            drivers.driverId         11371          0                 0                     0                []    True

0 of 23 foreign-key checks failed

### 3.4 Duplicate `(raceId, driverId)` rows in `results`, by year

Our modelling grain is one row per `(raceId, driverId)`. Here we count, per season,
the rows that violate it. Nothing is dropped; the rule for handling them is an open decision.

In [10]:
dups = with_year(find_duplicates(results, ["raceId", "driverId"]))

dup_by_year = pd.DataFrame({
    "n_duplicated_pairs": dups.drop_duplicates(["raceId", "driverId"]).groupby("year").size(),
    "n_rows_involved": dups.groupby("year").size(),
    "n_races_affected": dups.groupby("year")["raceId"].nunique(),
})
dup_by_year.loc["Total"] = dup_by_year.sum()
display(dup_by_year)

       n_duplicated_pairs  n_rows_involved  n_races_affected
year
1950                    4                8                 3
1951                    4                8                 2
1952                    3                6                 3
1953                   14               30                 5
1954                   16               33                 5
1955                   15               33                 4
1956                   12               24                 6
1957                    8               16                 5
1958                    3                6                 3
1960                    1                2                 1
1961                    2                4                 2
1962                    1                2                 1
1964                    1                2                 1
1978                    1                2                 1
Total                  85              176                42

Example duplicated entries (same driver, same race, more than one row):

In [11]:
example = dups.merge(
    tables["drivers"][["driverId", "driverRef"]], on="driverId", how="left", validate="many_to_one"
).merge(
    tables["constructors"][["constructorId", "constructorRef"]], on="constructorId", how="left", validate="many_to_one"
)
display(example[[
    "year", "raceId", "driverId", "driverRef", "constructorRef", "number",
    "grid", "positionText", "positionOrder", "points", "laps", "statusId",
]].head(12))

    year  raceId  driverId driverRef constructorRef  number  grid positionText  positionOrder  points  laps  statusId
0   1978     540       229      ertl            ats      10     0            F             26     0.0     0        81
1   1978     540       229      ertl         ensign      23     0            F             29     0.0     0        97
2   1964     717       373     clark   lotus-climax       1     1            7              7     0.0   102        60
3   1964     717       373     clark   lotus-climax       2     1            R             12     0.0    54        98
4   1962     733       465    greene   lotus-climax      48     0            W             22     0.0     0        54
5   1962     733       465    greene          gilby      50     0            W             25     0.0     0        54
6   1961     742       475      moss       ferguson      26    20            D             19     0.0    56         2
7   1961     742       475      moss   lotus-climax      28     5            R             21     0.0    44        23
8   1961     745       418   gregory   lotus-climax      22    11            R             17     0.0    23         6
9   1961     745       418   gregory   lotus-climax      21    15           11             11     0.0    92        18
10  1960     746       475      moss  cooper-climax      36     1            R             17     0.0    40        22
11  1960     746       475      moss  cooper-climax      38     8            3              3     0.0    80         1

### 3.5 Qualifying data: first year and coverage per season

Two coverage measures per season:

- **races covered**: share of races with *any* qualifying rows;
- **entries covered**: share of `results` rows (driver–race entries) whose
  `(raceId, driverId)` also appears in `qualifying`. This is what matters for our grain:
  it is the share of model rows that would have qualifying features.

In [12]:
quali_race_ids = set(qualifying["raceId"].dropna())
first_quali_year = int(races.loc[races["raceId"].isin(quali_race_ids), "year"].min())
print("First season with qualifying data:", first_quali_year)

quali_pairs = qualifying[["raceId", "driverId"]].drop_duplicates().assign(has_quali=True)
entries = with_year(results[["raceId", "driverId"]]).merge(
    quali_pairs, on=["raceId", "driverId"], how="left", validate="many_to_one"
)
assert len(entries) == len(results), "join changed the row count"
entries["has_quali"] = entries["has_quali"].fillna(False).astype(bool)

races_with_results = set(results["raceId"])
season = races.assign(
    has_results=races["raceId"].isin(races_with_results),
    has_quali=races["raceId"].isin(quali_race_ids),
)
quali_cov = pd.DataFrame({
    "n_races": season.groupby("year").size(),
    "n_races_with_results": season.groupby("year")["has_results"].sum(),
    "n_races_with_quali": season.groupby("year")["has_quali"].sum(),
    "n_results_rows": entries.groupby("year").size(),
    "n_results_rows_with_quali": entries.groupby("year")["has_quali"].sum(),
}).fillna(0).astype(int)
quali_cov["pct_races_covered"] = (100 * quali_cov["n_races_with_quali"] / quali_cov["n_races"]).round(1)
quali_cov["pct_entries_covered"] = (
    100 * quali_cov["n_results_rows_with_quali"] / quali_cov["n_results_rows"].replace(0, np.nan)
).round(1)
display(quali_cov)

First season with qualifying data: 1994

      n_races  n_races_with_results  n_races_with_quali  n_results_rows  n_results_rows_with_quali  pct_races_covered  pct_entries_covered
year
1950        7                     7                   0             160                          0                0.0                  0.0
1951        8                     8                   0             179                          0                0.0                  0.0
1952        8                     8                   0             215                          0                0.0                  0.0
1953        9                     9                   0             246                          0                0.0                  0.0
1954        9                     9                   0             230                          0                0.0                  0.0
1955        7                     7                   0             180                          0                0.0                  0.0
1956        8                     8                   0             190                          0                0.0                  0.0
1957        8                     8                   0             171                          0                0.0                  0.0
1958       11                    11                   0             241                          0                0.0                  0.0
1959        9                     9                   0             195                          0                0.0                  0.0
1960       10                    10                   0             223                          0                0.0                  0.0
1961        8                     8                   0             220                          0                0.0                  0.0
1962        9                     9                   0             223                          0                0.0                  0.0
1963       10                    10                   0             254                          0                0.0                  0.0
1964       10                    10                   0             207                          0                0.0                  0.0
1965       10                    10                   0             205                          0                0.0                  0.0
1966        9                     9                   0             166                          0                0.0                  0.0
1967       11                    11                   0             205                          0                0.0                  0.0
1968       12                    12                   0             233                          0                0.0                  0.0
1969       11                    11                   0             177                          0                0.0                  0.0
1970       13                    13                   0             294                          0                0.0                  0.0
1971       11                    11                   0             263                          0                0.0                  0.0
1972       12                    12                   0             309                          0                0.0                  0.0
1973       15                    15                   0             357                          0                0.0                  0.0
1974       15                    15                   0             436                          0                0.0                  0.0
1975       14                    14                   0             363                          0                0.0                  0.0
1976       16                    16                   0             434                          0                0.0                  0.0
1977       17                    17                   0             477                          0                0.0                  0.0
1978       16                    16                   0             471                          0                0.0                  0.0
1979       15                    15                   0             403                          0                0.0                  0.0
1980       14                    14                   0             383                          0                0.0                  0.0
1981       15                    15                   0             449                          0                0.0                  0.0
1982       16                    16                   0             465                          0                0.0                  0.0
1983       15                    15                   0             424                          0                0.0                  0.0
1984       16                    16                   0             430                          0                0.0                  0.0
1985       16                    16                   0             406                          0                0.0                  0.0
1986       16                    16                   0             412                          0                0.0                  0.0
1987       16                    16                   0             419                          0                0.0                  0.0
1988       16                    16                   0             495                          0                0.0                  0.0
1989       16                    16                   0             620                          0                0.0                  0.0
1990       16                    16                   0             542                          0                0.0                  0.0
1991       16                    16                   0             539                          0                0.0                  0.0
1992       16                    16                   0             478                          0                0.0                  0.0
1993       16                    16                   0             412                          0                0.0                  0.0
1994       16                    16                  15             444                        392               93.8                 88.3
1995       17                    17                  17             418                        418              100.0                100.0
1996       16                    16                   7             340                        148               43.8                 43.5
1997       17                    17                  10             376                        220               58.8                 58.5
1998       16                    16                   7             349                        153               43.8                 43.8
1999       16                    16                   3             352                         65               18.8                 18.5
2000       17                    17                   4             373                         88               23.5                 23.6
2001       17                    17                   1             374                         22                5.9                  5.9
2002       17                    17                   2             362                         42               11.8                 11.6
2003       16                    16                  16             320                        320              100.0                100.0
2004       18                    18                  18             360                        360              100.0                100.0
2005       19                    19                  19             376                        376              100.0                100.0
2006       18                    18                  18             396                        396              100.0                100.0
2007       17                    17                  17             374                        374              100.0                100.0
2008       18                    18                  18             368                        368              100.0                100.0
2009       17                    17                  17             340                        340              100.0                100.0
2010       19                    19                  19             456                        456              100.0                100.0
2011       19                    19                  19             456                        452              100.0                 99.1
2012       20                    20                  20             480                        476              100.0                 99.2
2013       19                    19                  19             418                        418              100.0                100.0
2014       19                    19                  19             407                        405              100.0                 99.5
2015       19                    19                  19             378                        374              100.0                 98.9
2016       21                    21                  21             462                        457              100.0                 98.9
2017       20                    20                  20             400                        398              100.0                 99.5
2018       21                    21                  21             420                        420              100.0                100.0
2019       21                    21                  21             420                        418              100.0                 99.5
2020       17                    17                  17             340                        340              100.0                100.0
2021       22                    22                  22             440                        439              100.0                 99.8
2022       22                    22                  22             440                        440              100.0                100.0
2023       22                    22                  22             440                        440              100.0                100.0
2024       24                    24                  24             479                        479              100.0                100.0

### 3.6 `grid = 0` by decade

`grid = 0` has no single documented meaning (e.g. pit-lane start vs. did not start).
We only count it here; how to treat it is an open decision.

In [13]:
grid = with_year(results[["raceId", "grid"]])
grid["decade"] = (grid["year"] // 10 * 10).astype(int)
grid_by_decade = grid.groupby("decade").agg(
    n_results_rows=("grid", "size"),
    n_grid_null=("grid", lambda s: int(s.isna().sum())),
    n_grid_zero=("grid", lambda s: int((s == 0).sum())),
)
grid_by_decade["pct_grid_zero"] = (100 * grid_by_decade["n_grid_zero"] / grid_by_decade["n_results_rows"]).round(2)
display(grid_by_decade)

        n_results_rows  n_grid_null  n_grid_zero  pct_grid_zero
decade
1950              2007            0           68           3.39
1960              2113            0          198           9.37
1970              3807            0          351           9.22
1980              4503            0          571          12.68
1990              4250            0          357            8.4
2000              3643            0            8           0.22
2010              4297            0           28           0.65
2020              2139            0           57           2.66

### 3.7 Findings → open decisions

*To be filled in after reviewing the outputs above.*

| Finding | Evidence (section) | Open decision | Proposed rule | Status |
|---|---|---|---|---|
| … | 3.4 | Shared-drive rule | … | Pending |
| … | 3.5 | Missing-qualifying strategy / training window | … | Pending |
| … | 3.6 | Meaning of `grid = 0` | … | Pending |